<?php

namespace Tests\Feature\EA;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

class CreateBookEntryTest extends TestCase
{
    /**
     * A basic feature test example.
     *
     * @return void
     */
    public function testExample()
    {
        $response = $this->get('/');

        $response->assertStatus(200);
    }

    public function setUp(): void
    {
      parent::setUp(); // TODO: Change the autogenerated stub
      $this->setBaseRoute('ea');
      $this->setBaseModel('App\Models\EA');
    }

    public function a_user_can_create_a_bookentry(){
      $this->signIn();
      $this->create();
    }

    public function an_unauthenticated_user_cannot_create_a_bookentry(){
      $this->create();
    }

    public function a_demo_require_a_name(){
      $this->signIn();
      $this->post(route('ea.store'),[])->assertSessionHasErrors('name');
    }
}
