<?php

namespace Tests\Feature\EA;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

class UpdateBookEntryTest extends TestCase
{
  use WithFaker;

  private $attributes=[];

    public function setUp(): void
    {
      parent::setUp(); // TODO: Change the autogenerated stub
      $this->setBaseRoute('ea');
      $this->setBaseModel('App\Models\EA');
      $this->attributes=[
        'entry_date' => $this->faker->date(),
        'subaccount' => $this->faker->numberBetween(1,5),
        'opening_amount' => $this->faker->numberBetween(1000,5000),
        'closing_amount' => $this->faker->numberBetween(7000,9000),
        'cash_withdraw' => $this->faker->numberBetween(0,2000),
      ];
    }

    public function a_user_can_update_a_bookentry(){
      $this->signIn();
      $this->update($this->attributes);
    }

    public function an_unauthenticated_user_cannot_update_a_bookentry(){
      $this->update($this->attributes);
    }
}
